// USER
export const SET_AUTH = 'SET_AUTH';
export const SET_USER = 'SET_USER';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT = 'LOGOUT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

//SERIES
export const FETCH_SERIES_BY_ID_SUCCESS = 'FETCH_SERIES_BY_ID_SUCCESS';
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_BY_ID = 'FETCH_SERIES_BY_ID';
export const FETCH_SERIES = 'FETCH_SERIES';
export const FOLLOW_SERIES = 'FOLLOW_SERIES';
export const FOLLOW_SERIES_SUCCESS = 'FOLLOW_SERIES_SUCCESS';

//COMICS
export const FOLLOW_COMIC = 'FOLLOW_COMIC';
export const READ_ALL_COMIC = 'READ_ALL_COMIC';
export const FETCH_HOME_COMICS = 'FETCH_HOME_COMICS';
export const FETCH_HOME_COMICS_SUCCESS = 'FETCH_HOME_COMICS_SUCCESS';


export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const PLACE = {
    SERIES:1,
    HOME:2
};