//SERIES
export const FETCH_SERIES_BY_ID_SUCCESS = 'FETCH_SERIES_BY_ID_SUCCESS';
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_BY_ID = 'FETCH_SERIES_BY_ID';
export const FETCH_SERIES = 'FETCH_SERIES';